backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

local_backend: true

collections:
  - name: "site"
    label: "Nettsideinnhold"
    files:
      - file: "data/articles.json"
        name: "articles"
        label: "Artikler"
        fields:
          - label: "Artikler"
            name: "articles"
            widget: list
            summary: "{{fields.title}}"
            fields:
              - {label: "Tittel", name: "title", widget: "string"}
              - {label: "Ingress", name: "excerpt", widget: "text"}
              - {label: "Kategori", name: "tag", widget: "string"}
              - {label: "Dato", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false}
              - {label: "Bilde", name: "image", widget: "image", required: false}
              - {label: "Innhold", name: "body", widget: "markdown", required: false}
